// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xznijkzixjkhreftpkyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bmlqa3ppeGpraHJlZnRwa3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjQxNjQsImV4cCI6MjA2NTkwMDE2NH0.xwqYNI6rgiURGoJrA-Qvs5ANt-YlOWkhRVCqCuL1_IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);